version: '3'
services:
  postgres:
    image: 'postgres:12'
    container_name: 'java-postgres'
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=2222222222'
        - 'POSTGRES_DB=new'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
